### PR TITLE
Fixed Scenario(s) variable naming

### PR DESCRIPTION
**Pull request by brandonhoughton**
The docker file defines `$SCENARIOS` where as the `scenario.sh` entrypoint defines `$SCENARIO` despite the container's scenario folder defined as `$SCENARIOS`
Re-named the variable in `entrypoint.sh` to `$SERVER_SCENARIO`

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I merged #1 so you can cleanly rebase this PR and then it can be merged.

**Comment by brandonhoughton** [comment]
@SuperSandro2000 Rebased!

**Comment by Fank** [comment]
@brandonhoughton but could you please open the PR against https://github.com/dtandersen/docker_factorio_server .
Currently this is only for testing the travis ci integration, we will not continue maintaining it.
See https://github.com/dtandersen/docker_factorio_server/issues/229#issuecomment-488607081

**Comment by brandonhoughton** [comment]
This PR addresses an issue only on the ci+others branch, as well as a future issue with hadolint. 

I've opened the PR against [https://github.com/dtandersen/docker_factorio_server](https://github.com/dtandersen/docker_factorio_server) I'm assuming that including the Travis CI integration changes in the base is OK for now

**Pull request closed without merging**
